### ISSUE TITLE
import_EDF duplicates data every other second

### ISSUE THREAD

**Issue by faimai00** [amisepa/import_edf#1]
Dear Cedric,

There is an issue with this function. 
For some files, import_EDF reads the data and annotations correctly. 
For some files, however, it reads the data wrongly every other second i.e. the first, third, fifth etc seconds of data are identical to data read in EDFbrowser, but the second, fourth, sixth etc seconds of data are different. 
I think what happens is that every other second of the data is the same as the previous second, i.e. the data between seconds 1 and 2 is identical to that between 0 and 1, the data between seconds 3-4 is identical to that between 2-3 etc.

A colleague of mine suggested that this might be because of the assumption that the sample window is 1s in EDF files (which it often is, but in some cases it can be 2s). This can vary quite widely in EDF, e.g. depending upon the sampling frequency and/or the number of channels, or perhaps an interaction of those two factors but we're not 100% sure - my colleague has seen some exports where it has made the sample window 0.25s.

Please do you think there might be a way to correct this? 
This window doesn't let me upload any .edf files but I am happy to send some of the data in question through someplace else?

I would deeply appreciate any help.

Best wishes,
Irene

**Comment by amisepa** [comment]
Sorry to hear that. Could you send a drive link with 2 or 3 different files where this happens? 

I should be able to correct that.

**Comment by faimai00** [comment]
Dear Cedric,

Many thanks. I have created a Drive folder with the files: https://drive.google.com/drive/folders/1B0hrWeBeVnG8EFx2yvS9r_d42yfA2khu?usp=sharing 

RKS09, RKS54 and RKS87 are all read incorrectly as described above. 
In contrast, RKS174, RKS50 are read correctly. 

My colleague suggests that the bug is introduced at lines 185-186:
"What they are doing here is trying to loop over 1s segments within the chunks of data stored in the .edf file, indexing which second they are up to using "iSec".  This works for the first second within each chunk of data as iSec=1 and iSec+sRate-1 is the correct sample number within the chunk of data at which to end that second's sample.  However, for the next second of data, iSec now equals 2, so the index into the chunk of data on line 186 looks for data from sample 2 to sample 2+sRate-1, in other words, it just shifts the data it returns by one sample.  That's why you get the first and second of data looking almost identical.
You can correct this bug by indexing correctly in line 186, something like:
    eegData(iChan, sample:sample+sRate-1) = cellData(((iSec-1)*sRate+1):(iSec*sRate));

Now, as iSec goes up, the start and end point for the sampling goes up to the correct value and the correct data are returned."

However, this will only work for EDF files where the sampling rate is a round number of seconds so it is not a generalisable strategy. There is no a priori reason from the EDF (or EDF+) spec why that should be the case, and we have seen EDF files with fractional numbers of seconds as the data window size. 

I hope this helps as a start! 

Thank you very much for your help.

Best wishes,
Irene

**Comment by faimai00** [comment]
Additionally, I have noticed that for certain files (e.g. RKS76 and RKS85 in the drive), the events are still read incorrectly (wrong latency) and sometimes (RKS76) boundaries are added in spite of the file being continuous (EDF+C). 

I attach an example (RKS85) where you can see that the discontinuity is at second 65, whilst the boundary in EEGlab gets placed at second 52:
![Screenshot 2022-05-16 at 16 05 43](https://user-images.githubusercontent.com/63585229/168624234-63fe18c1-0673-43b2-a616-84e3435cda31.png)

Would you have any idea why that might be the case? 
I really appreciate your help.

Best wishes,
Irene

**Comment by amisepa** [comment]
Hi, Sorry I have been really busy. This shouldn't be too hard to fix, I'll try to take a look next week.

**Comment by amisepa** [comment]
Hi @faimai00, I finally found some time to work on this, sorry it's been so long...
I think I fixed all the issues. I made some significant changes and took a different approach. 

Where I am not 100% sure it's correct is for the discontinuous files, it looks ok when I look at the data (I remove the flat segments directly instead of looking for gaps in the EDF timestamps). But I get an eror from eeglab doing the last checks, about minor discrepencies in event latencies. 

Regarding continuous files that had cells with 2 s of data (e.g., RKS09), I think it is fixed now.

Please run some more tests and let me know!

Cedric
