### ISSUE TITLE
Segmented EDF Dataset

### ISSUE THREAD

**Issue by EfthymiosGitHub** [amisepa/import_edf#5]
These are two edf files that are segmented and in need of a sequential connection (follow the link: https://www.dropbox.com/scl/fo/mr3i9623txfvtfc8m2q0t/h?rlkey=wxr7pwymcwhmy33n6dmasjnmk&dl=0 ).

**Comment by amisepa** [comment]
Sorry I haven't had the time to look into this. I can give it a try if you want to upload your data again.

**Comment by EfthymiosGitHub** [comment]
Dear Cedric, 

Thank you for this email. I managed to solve the problem by reconfiguring the software parameters of the EEG unit I am using. It was actually a code bug. Thank you once again for your interest! 

Best, 
Efthymios

**Comment by amisepa** [comment]
Ok glad to hear you solved the problem.
