### ISSUE TITLE
Another edfread function? 

### ISSUE THREAD

**Issue by lopezchau** [amisepa/import_edf#6]
Hello world.
Totally new to EEGLab.  I get this message as soon as I tried to import a file. (The plugin works fine, is am just curious on why I am not able to prevent it from appearing)
<img width="412" alt="Captura de pantalla 2024-05-05 a la(s) 8 00 55 p  m" src="https://github.com/amisepa/import_edf/assets/143896040/b1811214-2432-4ff4-97a0-ab62c64fc22a">

I tried to remove tools/signal/signal from Matlab path (where a edfread file is) , but it does not work.

I am using MacOS Sonoma 14.4.1 , Matlab r2024a and import_edf 1.3 

Any help would be greatly appreciated.

**Comment by amisepa** [comment]
No don't remove the Matlab path. This means you have another external function on your computer called edfread, from another toolbox for example. 

type this in your command window and it should give you the path to the other file to remove. 

`which('edfread')`

**Comment by lopezchau** [comment]
> No don't remove the Matlab path. This means you have another external function on your computer called edfread, from another toolbox for example.
> 
> type this in your command window and it should give you the path to the other file to remove.
> 
> `which('edfread')`

Thank you very much for your answer.

Indeed this is what I tried to figure out that is the folder that I tried to remove from path

<img width="1000" alt="Captura de pantalla 2024-05-06 a la(s) 3 12 44 p  m" src="https://github.com/amisepa/import_edf/assets/143896040/30edc8d2-651b-46b5-a02e-2fbec4d62f58">


But when I remove that folder from the path, I get this message


<img width="520" alt="Captura de pantalla 2024-05-06 a la(s) 3 15 16 p  m" src="https://github.com/amisepa/import_edf/assets/143896040/6e3bdce7-f413-49b5-be1c-c5a7d41e6acb">

**Comment by amisepa** [comment]
This edfread function is the right one that the plugin uses, don't remove it. There must be another one somewhere. 
Sorry, this is actually the right code line to see if there is another one with the same name on your path. 
`which('edfread', 'all')`

**Comment by lopezchau** [comment]
> This edfread function is the right one that the plugin uses, don't remove it. There must be another one somewhere. Sorry, this is actually the right code line to see if there is another one with the same name on your path. `which('edfread', 'all')`

Thank you very much again.  After running that command, this is what I get: 

<img width="747" alt="Captura de pantalla 2024-05-07 a la(s) 7 53 44 a  m" src="https://github.com/amisepa/import_edf/assets/143896040/4b1d0cba-3bc3-44c6-ad4d-f7f031a5ceee">

It seems that is the only one....

**Comment by amisepa** [comment]
Sorry about that, I did a test by creating a fake edfread function and adding it to my path, and it still detected only one with the highest priority. I added code to the plugin with a better solution to detect multiple edfread functions. Can you reinstall it from the github repository and try again? https://github.com/amisepa/import_edf
You have to remove the previous import_edf folder, download it again to get the new changes, and unzip it in the EEGLAB>plugins folder. 
(or simply pull new changes if you use Git).

Let me know if this works

**Comment by lopezchau** [comment]
> Sorry about that, I did a test by creating a fake edfread function and adding it to my path, and it still detected only one with the highest priority. I added code to the plugin with a better solution to detect multiple edfread functions. Can you reinstall it from the github repository and try again? https://github.com/amisepa/import_edf You have to remove the previous import_edf folder, download it again to get the new changes, and unzip it in the EEGLAB>plugins folder. (or simply pull new changes if you use Git).
> 
> Let me know if this works

It worked!  Thank you very much!.

Just wanted to let you know that I switched to your plugin from Biosig because yours import Events information much accurately.

Congratulations and thank you very much again.

**Comment by amisepa** [comment]
Glad to hear it, thank you!  
And thanks for reporting the error. The new check is more robust now.
